# base image 
FROM continuumio/miniconda3

# metadata
LABEL base.image="miniconda3"
LABEL version="1"
LABEL software="SARS-CoV2 Illumina GeNome Assembly Line (SIGNAL)"
LABEL software.version="1.1.0"
LABEL description="SARS-CoV2 Genome Analysis Workflow"
LABEL website="https://github.com/jaleezyy/covid-19-signal"
LABEL documentation="https://github.com/jaleezyy/covid-19-signal/README.md"
LABEL license="https://github.com/jaleezyy/covid-19-signal/LICENSE"
LABEL tags="Genomics"

# maintainer
MAINTAINER Finlay Maguire <finlaymaguire@gmail.com>

# get some system essentials
RUN apt-get update && apt-get install -y curl wget git build-essential && conda init bash

# install snakemake and system dependencies
RUN conda install --channel conda-forge mamba
RUN mamba create --name signal --channel conda-forge --channel bioconda snakemake>5.19.0 pandas conda

# clone the workflow repo (tag later to specific release to match software version)
RUN git clone https://github.com/jaleezyy/covid-19-signal

# set workdir to pipeline folder in repo
WORKDIR covid-19-signal

# install all snakemake rule conda envs using dummy snakemake file
RUN conda config --set channel_priority strict
RUN conda run -n signal snakemake --verbose --conda-frontend mamba --use-conda --conda-prefix=$HOME/.snakemake -s resources/dependencies --cores 1

